[pytest]

addopts = --rootdir=.
pythonpath = .
testpaths = tests
markers =
    no_clean: desabilita o cleanup automático da fixture clean_db para este teste
    override_rate_limiter: não sobrescreve o rate_limiter do app principal para este teste